// AUTO-GENERATED by operators/example-uploader
// Do not edit manually — run `npm run upload` from the operator to regenerate.
// These case studies are merged with the hardcoded ones in _caseStudies.ts

import type { ExampleCaseStudy } from "./_caseStudies"

export type GeneratedCaseStudy = ExampleCaseStudy & { isClaimed: boolean }

export const generatedCaseStudies: GeneratedCaseStudy[] = [
  {
    "slug": "school-of-skill",
    "category": "Health & fitness",
    "title": "Built to feel like an organisation, not just a coach",
    "business": "School of Skill",
    "location": "Birmingham",
    "description": "A youth basketball development brand repositioned from grassroots coaching to credible, scalable organisation.",
    "goal": "School of Skill had proven demand but looked self-made. They needed a brand and website that felt professional enough for schools, parents, and strategic partners—credible, structured, and ready to grow beyond the founder.",
    "solution": "Sorted built a clean, editorial site with white space, strong photography, and clear service pillars. The rebrand positioned School of Skill as a serious British organisation with international reach, not just another coaching page.",
    "testimonial": "We went from looking like a Facebook page to looking like a real organisation. The site gives us credibility with schools and parents we didn't have before. It's helped us have completely different conversations.",
    "testimonialName": "Dalian Mason",
    "testimonialRole": "Founder, School of Skill",
    "stats": [
      [
        "24hrs",
        "First homepage concept delivered"
      ],
      [
        "3",
        "Service pillars clarified and structured"
      ],
      [
        "100%",
        "White-led design for professional presence"
      ],
      [
        "4",
        "Audience groups now clearly addressed"
      ]
    ],
    "image": "/examples/live/school-of-skill-desktop.png",
    "screenshots": {
      "desktop": "/examples/live/school-of-skill-desktop.png",
      "tablet": "/examples/live/school-of-skill-tablet.png",
      "mobile": "/examples/live/school-of-skill-mobile.png"
    },
    "liveUrl": "https://schoolofskill.co.uk",
    "isClaimed": true
  },
  {
    "slug": "a-good-catch",
    "category": "Hospitality",
    "title": "Built to get the order, not just look good",
    "business": "A Good Catch",
    "location": "London",
    "description": "A complete Hawaiian poke bowl restaurant website with ordering built in, not bolted on.",
    "goal": "A Good Catch needed a website that makes ordering poke bowls simple and obvious. Not a brochure with a hidden menu. The site had to work as hard on mobile as it does on desktop, because that's where hungry people order lunch.",
    "solution": "Sorted built a full ordering experience across nine pages: menu browsing, bowl customisation, locations, catering, rewards, and checkout flow. The design extends a premium food-first visual system across the entire site. Order Now sits in the navigation and repeats where it matters. The customisation flow breaks down protein, toppings, and sauces without overwhelming the customer.",
    "testimonial": "This is exactly what we'd want if we were launching tomorrow. The ordering journey makes sense, the food looks incredible, and nothing gets in the way of placing an order. If this is what Sorted can build speculatively, we'd be confident commissioning the real thing.",
    "testimonialName": "A Good Catch",
    "testimonialRole": "Pending response",
    "stats": [
      [
        "24hrs",
        "First homepage concept delivered"
      ],
      [
        "9",
        "Complete pages built"
      ],
      [
        "3",
        "Ordering steps from browse to cart"
      ],
      [
        "100%",
        "Mobile-optimised ordering flow"
      ]
    ],
    "image": "/examples/live/a-good-catch-desktop.png",
    "screenshots": {
      "desktop": "/examples/live/a-good-catch-desktop.png",
      "tablet": "/examples/live/a-good-catch-tablet.png",
      "mobile": "/examples/live/a-good-catch-mobile.png"
    },
    "liveUrl": "https://agoodcatch.netlify.app",
    "isClaimed": false
  },
  {
    "slug": "bridge-growth",
    "category": "Professional",
    "title": "Built to position the operator, not the pitch",
    "business": "Bridge Growth",
    "location": "London",
    "description": "A B2B consultancy website that positions Nathan as a revenue operator helping tech founders build sales systems beyond themselves.",
    "goal": "Bridge needed a site that separated Nathan from generic sales agencies. The proposition wasn't outsourced help — it was building a revenue engine that doesn't depend on the founder. That required a different visual language entirely.",
    "solution": "Sorted built a dual-environment site: dark brand moments for impact, light editorial layouts for authority. The homepage integrates Nathan's workshops, podcast, and insights into one founder platform. Every section reinforces the central idea: your pipeline shouldn't depend on you.",
    "testimonial": "This doesn't look like the agency sites we've seen. It actually positions us as operators, not vendors. The dark-to-light rhythm works, the content feels editorial, and the founder events section shows we're not just talking about this stuff — we're doing it.",
    "testimonialName": "Bridge Growth",
    "testimonialRole": "Pending response",
    "stats": [
      [
        "24hrs",
        "First homepage concept delivered"
      ],
      [
        "2",
        "Visual environments that alternate throughout"
      ],
      [
        "6",
        "Integrated authority platforms on homepage"
      ],
      [
        "100%",
        "Built from approved mockup as source"
      ]
    ],
    "image": "/examples/live/bridge-growth-desktop.png",
    "screenshots": {
      "desktop": "/examples/live/bridge-growth-desktop.png",
      "tablet": "/examples/live/bridge-growth-tablet.png",
      "mobile": "/examples/live/bridge-growth-mobile.png"
    },
    "liveUrl": "https://bridgegrowth.netlify.app",
    "isClaimed": false
  },
  {
    "slug": "warwickshire-str",
    "category": "Hospitality",
    "title": "Built to turn visitors into enquiries",
    "business": "Warwickshire Short Stays",
    "location": "Warwickshire",
    "description": "A clean, direct website for short-term accommodation that turns property browsers into booking enquiries.",
    "goal": "Warwickshire Short Stays needed a website that explained what they offer without pushing people into instant checkout. Their guests—relocators, contractors, families between homes—want to ask questions before booking. The site had to build trust and make contact easy.",
    "solution": "Sorted built a Next.js site with clear property listings, enquiry forms on every page, and one-tap phone and WhatsApp contact. Each property has its own detailed page. No fake urgency, no checkout pressure. Just clean information and simple ways to get in touch.",
    "testimonial": "We needed something straightforward that made it easy for people to contact us. Sorted delivered exactly that. The site looks professional, loads fast, and we're getting enquiries from the right people.",
    "testimonialName": "Warwickshire Short Stays",
    "testimonialRole": "Property Owner",
    "stats": [
      [
        "24hrs",
        "First homepage concept delivered"
      ],
      [
        "3",
        "Ways to contact from every page"
      ],
      [
        "100%",
        "Direct enquiries, no booking fees"
      ],
      [
        "8",
        "Property pages with full details"
      ]
    ],
    "image": "/examples/live/warwickshire-str-desktop.png",
    "screenshots": {
      "desktop": "/examples/live/warwickshire-str-desktop.png",
      "tablet": "/examples/live/warwickshire-str-tablet.png",
      "mobile": "/examples/live/warwickshire-str-mobile.png"
    },
    "liveUrl": "https://warwickshireshortstays.co.uk",
    "isClaimed": true
  }
]
