// ─────────────────────────────────────────────────────────────
// Example Uploader — Publish Module
// Writes generated case studies to a TypeScript data file
// and upserts example rows into Supabase.
// ─────────────────────────────────────────────────────────────

import fs from "node:fs";
import path from "node:path";
import { createClient } from "@supabase/supabase-js";
import type { GeneratedCaseStudy, SiteSource } from "./types.js";

const GENERATED_FILE_REL = "app/examples/_generatedCaseStudies.ts";

function generateTsFile(caseStudies: GeneratedCaseStudy[]): string {
  const header = `// AUTO-GENERATED by operators/example-uploader
// Do not edit manually — run \`npm run upload\` from the operator to regenerate.
// These case studies are merged with the hardcoded ones in _caseStudies.ts

import type { ExampleCaseStudy } from "./_caseStudies"

export type GeneratedCaseStudy = ExampleCaseStudy & { isClaimed: boolean }

export const generatedCaseStudies: GeneratedCaseStudy[] = `;

  // Serialize with proper formatting
  const json = JSON.stringify(caseStudies, null, 2);
  // Convert to TS-compatible object literal (JSON is valid TS)
  return `${header}${json}\n`;
}

export function publishCaseStudies(
  repoRoot: string,
  caseStudies: GeneratedCaseStudy[],
  dryRun: boolean,
  verbose: boolean,
): void {
  const filePath = path.join(repoRoot, GENERATED_FILE_REL);

  // Merge with existing generated case studies (preserve ones not in this batch)
  let existing: GeneratedCaseStudy[] = [];
  if (fs.existsSync(filePath)) {
    try {
      // Read and extract the array via require/eval — safe since we generated it
      const content = fs.readFileSync(filePath, "utf-8");
      const match = content.match(/generatedCaseStudies:\s*GeneratedCaseStudy\[\]\s*=\s*(\[[\s\S]*\])/);
      if (match) {
        existing = JSON.parse(match[1]!) as GeneratedCaseStudy[];
      }
    } catch {
      // ignore parse errors, start fresh
    }
  }

  // Merge: replace entries with same slug, keep others
  const bySlug = new Map<string, GeneratedCaseStudy>();
  for (const cs of existing) bySlug.set(cs.slug, cs);
  for (const cs of caseStudies) bySlug.set(cs.slug, cs);

  const merged = Array.from(bySlug.values());
  const tsContent = generateTsFile(merged);

  if (dryRun) {
    if (verbose) {
      console.log(`  [publish] DRY RUN — would write ${merged.length} case studies to ${filePath}`);
    }
    return;
  }

  fs.writeFileSync(filePath, tsContent, "utf-8");
  if (verbose) {
    console.log(`  [publish] Wrote ${merged.length} case studies to ${filePath}`);
  }
}

export function publishToSupabase(
  sources: SiteSource[],
  blurbs: Map<string, string>,
  dryRun: boolean,
  verbose: boolean,
): void {
  const supabaseUrl = process.env.SUPABASE_URL || "https://qweevancxedkkfxysnzq.supabase.co";
  const serviceKey = process.env.SUPABASE_SERVICE_KEY;

  if (!serviceKey) {
    if (verbose) {
      console.log("  [publish] SUPABASE_SERVICE_KEY not set — skipping Supabase upsert");
    }
    return;
  }

  if (dryRun) {
    if (verbose) {
      console.log(`  [publish] DRY RUN — would upsert ${sources.length} rows to Supabase examples table`);
    }
    return;
  }

  const supabase = createClient(supabaseUrl, serviceKey);

  const rows = sources.map((s) => ({
    business_name: s.businessName,
    image_url: `/examples/live/${s.slug}-desktop.png`,
    type: s.isLive ? "live" : "mockup",
    live_url: s.liveUrl ?? null,
    category: s.category,
    storage_path: null,
    prospect_id: null,
  }));

  // Best-effort upsert — don't fail the whole run if Supabase is unavailable
  supabase
    .from("examples")
    .upsert(rows, { onConflict: "storage_path", ignoreDuplicates: false })
    .then(({ error }) => {
      if (error) {
        console.error(`  [publish] Supabase upsert failed: ${error.message}`);
      } else if (verbose) {
        console.log(`  [publish] Upserted ${rows.length} rows to Supabase examples table`);
      }
    });
}
