"use client"

import { demoSession } from "@/lib/sorted-updates"
import { useState } from "react"

export default function SortedPreviewPage() {
  const [changeId, setChangeId] = useState("")
  const [status, setStatus] = useState("")

  async function decide(decision: "approve" | "reject") {
    const response = await fetch("/api/sorted-updates/approval", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        client_id: demoSession.client_id,
        change_id: changeId,
        decision,
        decided_by: demoSession.email || "portal",
      }),
    })
    const payload = await response.json()
    setStatus(payload.message || payload.status || payload.error)
  }

  return (
    <main className="min-h-screen bg-[#171411] px-6 py-10 text-white">
      <div className="mx-auto max-w-4xl">
        <a href="/sorted/chat" className="text-sm font-bold text-white/60">Back to chat</a>
        <h1 className="mt-6 text-4xl font-black tracking-tight">Preview queue</h1>
        <p className="mt-4 max-w-2xl text-white/65">
          Preview branch metadata is generated by the Python operator. The next implementation step is to replace this queue scaffold with GitHub PR and Netlify deploy-preview data.
        </p>
        <section className="mt-8 rounded-[2rem] border border-white/10 bg-white/5 p-6">
          <p className="font-mono text-xs uppercase tracking-[0.18em] text-white/50">Infrastructure ready</p>
          <h2 className="mt-3 text-2xl font-black">Branch plans, PR titles, target files, and preview URLs have backend contracts.</h2>
          <div className="mt-6 rounded-3xl bg-white p-4 text-[#171411]">
            <label className="text-sm font-black">Change ID</label>
            <input value={changeId} onChange={(event) => setChangeId(event.target.value)} placeholder="chg_upd_portal_..." className="mt-2 w-full rounded-2xl border border-black/10 bg-[#fffaf0] px-4 py-3 text-sm outline-none" />
            <div className="mt-3 flex gap-2">
              <button onClick={() => decide("approve")} className="rounded-full bg-[#1d7f4f] px-4 py-2 text-sm font-black text-white">Approve preview</button>
              <button onClick={() => decide("reject")} className="rounded-full bg-[#8f241f] px-4 py-2 text-sm font-black text-white">Reject</button>
            </div>
            {status ? <p className="mt-3 text-sm text-[#756c5f]">{status}</p> : null}
          </div>
        </section>
      </div>
    </main>
  )
}
